# These are supported funding model platforms

github: [alexjorgef]
patreon: alexontech
open_collective: alexjorgef
ko_fi: alexjorgef
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
